# Form implementation generated from reading ui file 'ui\mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1601, 881))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.tabWidget.setObjectName("tabWidget")
        self.stockGroupTab = QtWidgets.QWidget()
        self.stockGroupTab.setObjectName("stockGroupTab")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.stockGroupTab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1591, 851))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.stockGroupLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.stockGroupLayout.setContentsMargins(0, 0, 0, 0)
        self.stockGroupLayout.setObjectName("stockGroupLayout")
        self.tabWidget.addTab(self.stockGroupTab, "")
        self.smartTab = QtWidgets.QWidget()
        self.smartTab.setObjectName("smartTab")
        self.tabWidget.addTab(self.smartTab, "")
        self.strongTradeTab = QtWidgets.QWidget()
        self.strongTradeTab.setObjectName("strongTradeTab")
        self.tabWidget.addTab(self.strongTradeTab, "")
        self.chartTab = QtWidgets.QWidget()
        self.chartTab.setObjectName("chartTab")
        self.tabWidget.addTab(self.chartTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.stockGroupTab), _translate("MainWindow", "族群"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.smartTab), _translate("MainWindow", "智慧單"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.strongTradeTab), _translate("MainWindow", "搶單"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.chartTab), _translate("MainWindow", "線圖"))
